### ISSUE TITLE
Broken publicurl for things.stimuli

### ISSUE THREAD

**Issue by kbegany** [courtois-neuromod/things.stimuli#5]
I'm getting this error when I attempt to use `datalad get` on the zipped image files. The publicurl may not be set up or may be broken.

https://github.com/courtois-neuromod/things.stimuli/tree/f8f5162f79fb2e9fb0d8cbb8bac610db11a54180

`cneuromod-things/THINGS/fmriprep/sourcedata/things/stimuli$ datalad get images_fmri.zip`
```
get(error): images_fmri.zip (file) [S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
cannot download content
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
cannot download content
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
cannot download content]
```

**Comment by MarieStLaurent** [comment]
Thanks for flagging this, we'll look into it!

**Comment by bpinsard** [comment]
Thanks for pointing that issue, it should now be fixed.
You can either reinstall the dataset or fixed it with `datalad update --merge && git-annex enableremote conp-ria-storage-http`.

**Comment by kbegany** [comment]
I'm still having issues, in the main branch I get the error
```
/large_experiments/brainai/shared/studies/stlaurent2025/download/cneuromod-things/THINGS/fmriprep/sourcedata/things$ datalad get *
get(impossible): sourcedata/things/* [path does not exist]
```

And then the above3 AWS error persists if I switch to this branch
https://github.com/courtois-neuromod/things.stimuli/tree/zipped_img

> Thanks for pointing that issue, it should now be fixed. You can either reinstall the dataset or fixed it with `datalad update --merge && git-annex enableremote conp-ria-storage-http`.

**Comment by MarieStLaurent** [comment]
Aye, you are correct, sorry for your trouble (and thanks for flagging it!)

- The zipped images should be pulled from the `zipped_img` branch (commit f8f5162)
- At the moment, `datalad get `attempts to pull the images from an Amazon S3 store (restricted access w password) rather than the CONP remote (open access), which is why it fails. We'll need to do the switch on our end for the download to process smoothly.

Meanwhile, if you are in a time crunch, a work around is to pull the images directly from the THINGS initiative database, right here: https://osf.io/jum2f/files/osfstorage

The `images_THINGS.zip` file includes every image that was shown to the CNeuroMod participants in the scanner (and many more!). Just read the LICENSE file and enter the passord they provide to unzip the files.

**Comment by bpinsard** [comment]
Not sure what is happening there.
`cd cneuromod-things/ && datalad get -n -r THINGS/fmriprep/`  should install the datasets recursively (seems like some stuffs are missing). 
`cd THINGS/fmriprep/sourcedata/things/stimuli && datalad update --merge && git-annex enableremote conp-ria-storage-http` should get the storage remotes right so that `datalad get images_fmri.zip`  works, and then unzip with Martin's password.

**Comment by kbegany** [comment]
Yay, this worked! Thanks so much 

> Not sure what is happening there. `cd cneuromod-things/ && datalad get -n -r THINGS/fmriprep/` should install the datasets recursively (seems like some stuffs are missing). `cd THINGS/fmriprep/sourcedata/things/stimuli && datalad update --merge && git-annex enableremote conp-ria-storage-http` should get the storage remotes right so that `datalad get images_fmri.zip` works, and then unzip with Martin's password.
